apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shopmate-prod
data:
  AWS_REGION: "ap-southeast-1"
  NODE_ENV: "production"
  PRODUCTS_TABLE: "shopmate-products-prod"
  CARTS_TABLE: "shopmate-carts-prod"
  ORDERS_TABLE: "shopmate-orders-prod"
  PRODUCT_SERVICE_URL: "http://product-service:3001"
  CART_SERVICE_URL: "http://cart-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"