apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: shopmate
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP