apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopmate
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP